### PR TITLE
Add a function to insert and return the generated key

### PR DESCRIPTION
**Pull request by rayokota**
I am trying to create a code generator using Angular, Chinook, and Sirocco (see https://github.com/rayokota/MicroFrameworkRosettaStone), and I need a function to perform an insert and return the generated key.

### CODE REVIEW

**Comment by mariogarcia** [comment]
Hi! Checking this now :)

**Comment by rayokota** [comment]
Thanks!

**Comment by mariogarcia** [comment]
I think it's ok. I think is going to be something really useful.

Just one more thing, Could you please change the PR to target branch `release_0_1_2` instead of master ? I need to do that to prepare the next release and deploy it to bintray. If everything is ready, I'll probably do it tomorrow.

BTW thanks for the contribution :)

**Comment by rayokota** [comment]
Ok, submitted another pull request, will close this one.  Thanks again!

**Pull request closed without merging**
